### ISSUE TITLE
Feature request: basic light mode for standalone query builder

### ISSUE THREAD

**Issue by akphi** [finos/legend-studio#1374]
### Similar requests

- [X] I have searched and found no existing similar requests

### What problems are you trying to solve?

The legacy tool where query builder is basing off has a light mode, we should consider adding a **simple** theme chooser to allow users switching between light/dark mode. This has fairly lots to do with styling more than doing the actual work of theming like in https://github.com/finos/legend-studio/issues/264

### Describe the solution you would like to see implemented

The following stylesheet is a good start

```scss
:root {
  --background: white;
  --header: #475b72;
  /* --btn--primary:  */
  --btn-text: rgb(41, 50, 58);
  --danger: rgb(197, 0, 0);
}


body {
  font-family: "Roboto Condensed", sans-serif;
  font-size: 13px;
  line-height: 1.3;
  color: rgb(41, 50, 58);
  background-color: rgb(246, 247, 248);
}


::-webkit-scrollbar {
  width: 11px;
  height: 11px;
}
::-webkit-scrollbar-thumb {
  height: 50px;
  background-color: rgb(181, 190, 196);
  outline-offset: -2px;
  border-radius: 4px;
  outline: rgb(237, 240, 241) solid 2px;
  border-width: 2px;
  border-style: solid;
  border-color: rgb(237, 240, 241);
  border-image: initial;
}
::-webkit-scrollbar-track-piece {
  background-color: rgb(237, 240, 241);
  border-radius: 0px;
}

.splitter-bar {
  display: flex;
  float: left;
  font-family: FontAwesome, sans-serif;
  font-size: medium;
  font-style: normal;
  font-weight: bolder;
  text-align: center;
  vertical-align: middle;
  justify-content: center;
  align-items: center;
  background: rgb(220, 226, 228);
  border-width: 1px;
  border-style: solid;
  border-color: rgb(181, 190, 196);
  border-image: initial;
}

// ----------------------- Panel -------------------------------

.panel-default > .panel-heading {
  color: rgb(41, 50, 58);
  background-color: rgb(237, 240, 241);
  border-color: rgb(220, 226, 228);
}

// ----------------------- Button -------------------------------

.btn-primary {
  background-image: linear-gradient(
    rgb(115, 153, 198) 0%,
    rgb(108, 148, 195) 100%
  );
  text-shadow: rgba(0, 0, 0, 0) 0px 0px 0px, rgba(0, 0, 0, 0.15) 0px 1px 0px;
  color: white;
  font-family: "Roboto Condensed", sans-serif;
  background-repeat: repeat-x;
  border-color: rgb(79, 127, 183);
}
.btn-primary:hover, .btn-primary:focus {
  box-shadow: rgba(0, 0, 0, 0.2) 0px 1px 1px;
  background-image: linear-gradient(rgb(104, 145, 194) 0%, rgb(97, 140, 191) 100%);
  color: white;
  background-repeat: repeat-x;
  border-color: rgb(68, 114, 168);
}

.btn,
.btn-default {
  background-image: linear-gradient(
    rgb(243, 246, 247) 0%,
    rgb(237, 241, 243) 100%
  );
  color: rgb(78, 90, 100);
  font-family: "Roboto Condensed", sans-serif;
  text-shadow: rgba(255, 255, 255, 0) 0px 0px 0px,
    rgba(255, 255, 255, 0.35) 0px 1px 0px;
  background-repeat: repeat-x;
  border-color: rgb(212, 223, 227);
}
.btn:hover, .btn:focus, .btn-default:hover, .btn-default:focus {
  box-shadow: rgba(0, 0, 0, 0.2) 0px 1px 1px;
  background-image: linear-gradient(rgb(234, 239, 241) 0%, rgb(228, 235, 237) 100%);
  color: rgb(78, 90, 100);
  background-repeat: repeat-x;
  border-color: rgb(197, 212, 216);
}

// run query button
.btn-success {
  background-image: linear-gradient(rgb(92, 182, 92) 0%, rgb(85, 179, 85) 100%);
  text-shadow: rgba(0, 0, 0, 0) 0px 0px 0px, rgba(0, 0, 0, 0.15) 0px 1px 0px;
  color: white;
  font-family: "Roboto Condensed", sans-serif;
  background-repeat: repeat-x;
  border-color: rgb(69, 154, 69);
}
.btn-success:hover, .btn-success:focus {
  box-shadow: rgba(0, 0, 0, 0.2) 0px 1px 1px;
  background-image: linear-gradient(rgb(81, 177, 81) 0%, rgb(77, 172, 77) 100%);
  color: white;
  background-repeat: repeat-x;
  border-color: rgb(61, 136, 61);
}

// ----------------------- Form -------------------------------

// selector
.form-control {
  display: block;
  width: 100%;
  height: 29px;
  font-size: 13px;
  line-height: 1.3;
  color: rgb(41, 50, 58);
  background-color: white;
  background-image: none;
  box-shadow: rgba(0, 0, 0, 0.075) 0px 1px 1px inset;
  padding: 5px 12px;
  border-width: 1px;
  border-style: solid;
  border-color: rgb(194, 201, 206);
  border-image: initial;
  border-radius: 0px;
  transition: border-color 0.15s ease-in-out 0s, box-shadow 0.15s ease-in-out 0s;
}

// ----------------------- Grid -------------------------------

.grid-header {
  font-family: "Roboto Condensed", sans-serif;
  font-weight: bold;
  font-size: 13px;
  min-height: 25px;
  color: rgb(78, 90, 100);
  background-color: rgb(220, 226, 228);
  box-shadow: rgba(0, 0, 0, 0.1) 0px 2px 1px 0px;
  z-index: 99;
}

.grid-header .grid-header-columns .grid-header-column {
  box-sizing: content-box;
  height: 100%;
  line-height: 25px;
  float: left;
  width: 100%;
  background-color: rgb(220, 226, 228);
  margin: 0px;
  padding: 0px 5px;
  border-top: 0px;
  border-bottom: 0px;
  border-left: 1px solid transparent;
  border-right: 1px solid rgb(206, 214, 217);
}

.grid-cell {
  border-right: 1px solid transparent;
  border-left: 1px solid transparent;
  border-bottom: 1px solid rgb(220, 226, 228);
  padding: 0px 5px;
  margin: 0px;
}

// ----------------------- Link and Actions -------------------------------

.editable-value {
  color: rgb(115, 153, 198);
  cursor: pointer;
  text-underline-position: under;
  text-decoration: underline dotted;
}
.actionable {
  color: rgb(115, 153, 198);
  cursor: pointer;
  text-underline-position: under;
  text-decoration: underline dotted;
}
.text-danger {
  color: rgb(197, 0, 0);
}
// header actions
.icon-action {
  color: rgb(115, 153, 198);
}
.icon-action:hover {
  color: rgb(27, 76, 140);
}

// ----------------------- Other -------------------------------

// color of the counter badge
.badge {
  display: inline-block;
  min-width: 10px;
  font-size: 11px;
  font-weight: bold;
  color: white;
  line-height: 1;
  vertical-align: middle;
  white-space: nowrap;
  text-align: center;
  background-color: rgb(144, 155, 164);
  padding: 3px 7px;
  border-radius: 3px;
}

// ------------------------ Modal -----------------------------

.modal-header .close {
  margin-top: 0px;
  color: rgb(40, 110, 204);
  font-size: 16px;
  line-height: 1.5;
  font-weight: 400;
  opacity: 1;
  height: 20px;
  width: 30px;
  text-indent: 100%;
  white-space: nowrap;
  text-shadow: none;
  position: relative;
  overflow: hidden;
}
.modal-footer {
  background-color: rgb(237, 240, 241);
  padding-top: 10px;
  padding-bottom: 10px;
}
.modal-footer {
  text-align: right;
  padding: 20px;
  border-top: 1px solid rgb(229, 229, 229);
}

// -------------------------- Code Block -----------------------

pre {
  display: block;
  font-size: 12px;
  line-height: 1.3;
  word-break: break-all;
  overflow-wrap: break-word;
  color: rgb(41, 50, 58);
  background-color: rgb(245, 245, 245);
  padding: 8px;
  margin: 0px 0px 8.5px;
  border-width: 1px;
  border-style: solid;
  border-color: rgb(204, 204, 204);
  border-image: initial;
  border-radius: 0px;
}
```

### Contribution

- [ ] I would like to work on this feature
