### ISSUE TITLE
Feature request: Remove prototype project support

### ISSUE THREAD

**Issue by akphi** [finos/legend-studio#879]
### Similar requests

- [X] I have searched and found no existing similar requests

### What problems are you trying to solve?

The concept of prototype projects was devised in the earliest day of the platform to accommodate for playgrounds, proof-of-concept. They cause code branching in both https://github.com/finos/legend-sdlc and https://github.com/finos/legend-studio

In SDLC, prototype projects and production projects must come from separate underlaying VCS instances. We could and should simplify the code by removing this distinction, and instead, having configuration per SDLC instance.

The code path in SDLC 

### Describe the solution you would like to see implemented

- [x] Refactor https://github.com/finos/legend-sdlc - https://github.com/finos/legend-sdlc/pull/383
- [x] Simplify fetching of projects
- [x] Simplify project creation dialog
- [x] https://github.com/finos/legend-studio/issues/408
- [x] Remove `TEMPORARY__useSDLCProductionProjectsOnly` and `TEMPORARY__useSDLCProductionProjectsOnly` flags
- [x] Deploy separate instances for prototype and production Gitlab for existing infrastructures

### Contribution

- [ ] I would like to work on this feature

**Comment by akphi** [comment]
We can use the following for `notfound` page

```jsx
  <div className="not-found-screen">
    <div className="not-found-screen__icon--ghost"><FontAwesomeIcon icon="ghost" /></div>
    <div className="not-found-screen__icon--ghost__shadow">
      <svg width="120px" height="40px" viewBox="0 0 600 400" xmlns="http://www.w3.org/2000/svg" version="1.1">
        <g transform="translate(300 200)">
          <ellipse className="not-found-screen__icon--ghost__shadow__inner" rx="320" ry="80" fill="#ebebeb"></ellipse>
        </g>
      </svg>
    </div>
    <div className="not-found-screen__text">Page not found</div>
  </div>
```

```css
.not-found-screen {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-self: center;
    padding: 100px;
    border: 1px solid var(--background);
    background-color: #fafafa;
}

.not-found-screen__icon--ghost {
    text-align: center;
    font-size: 120px;
    color: #f5d29b;
    animation: ghostbounce .9s alternate ease infinite !important;
}

.not-found-screen__icon--ghost__shadow {
    text-align: center;
}

.not-found-screen__icon--ghost__shadow__inner {
    animation: shadowgrow .9s alternate ease infinite !important;
}

.not-found-screen__text {
    font-family: 'Roboto Condensed';
    text-align: center;
    font-size: 20px;
    margin-top: 5px;
    color: #5a5a5a;
}

.not-found-screen__hint {
    font-family: 'Roboto Condensed';
    text-align: center;
    font-size: 14px;
    margin-top: 9px;
    color: #8a8a8a;
}

@keyframes ghostbounce {
	from { transform: translateY(5px); }
	to   { transform: translateY(-2px); }
}

@keyframes shadowgrow {
	from { transform: scale(1.1); }
	to   { transform: scale(1); }
}
```
